### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by vedranmiletic** [Umio-Yasuno/amdgpu_top#93]
`amdgpu_top` compiles fine on FreeBSD with drm-kmod package installed, but crashes on startup (`amdgpu` is module loaded via LinuxKPI). Here's the output:

```
% amdgpu_top
The AMDGPU driver is not loaded.
thread 'main' panicked at /home/testuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libamdgpu_top-0.9.0/src/device_path.rs:40:13:
explicit panic
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

% env RUST_BACKTRACE=1 amdgpu_top
The AMDGPU driver is not loaded.
thread 'main' panicked at /home/testuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libamdgpu_top-0.9.0/src/device_path.rs:40:13:
explicit panic
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

% env RUST_BACKTRACE=full amdgpu_top
The AMDGPU driver is not loaded.
thread 'main' panicked at /home/testuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libamdgpu_top-0.9.0/src/device_path.rs:40:13:
explicit panic
stack backtrace:
0:       0xd8e1cf767c - <unknown>
1:       0xd8e19cc3eb - <unknown>
2:       0xd8e1cf9992 - <unknown>
3:       0xd8e1cf7409 - <unknown>
4:       0xd8e1cfc550 - <unknown>
5:       0xd8e1cfd66b - <unknown>
6:       0xd8e1cf79d2 - <unknown>
7:       0xd8e1cf7929 - <unknown>
8:       0xd8e1cfcd66 - <unknown>
9:       0xd8e19d7682 - <unknown>
10:       0xd8e19d7805 - <unknown>
11:       0xd8e19d77a9 - <unknown>
12:       0xd8e1be27bd - <unknown>
13:       0xd8e18dfc5f - <unknown>
14:       0xd8e18c09c3 - <unknown>
15:       0xd8e18e1909 - <unknown>
16:       0xe10342ba6a - __libc_start1
17:       0xd8e18be63d - <unknown>
```

Any chance of FreeBSD support?

**Comment by Umio-Yasuno** [comment]
`amdgpu_top` gets the list of AMDGPU devices from `/sys/bus/pci/drivers/amdgpu/`.  
Does a similar interface exist on FreeBSD?

**Comment by Umio-Yasuno** [comment]
Could you try this branch?

https://github.com/Umio-Yasuno/amdgpu_top/tree/all_dri_dev

**Comment by vedranmiletic** [comment]
> `amdgpu_top` gets the list of AMDGPU devices from `/sys/bus/pci/drivers/amdgpu/`. Does a similar interface exist on FreeBSD?

`/sys` is not mounted, and `/compat/linux/sys` doesn't provide enough information. There are amdgpu variables available via `sysctl`, not sure if that helps.

> Could you try this branch?
> 
> https://github.com/Umio-Yasuno/amdgpu_top/tree/all_dri_dev

Sure, the result is:

```
% ./amdgpu_top
There are no the AMD GPU devices found.
thread 'main' panicked at src/main.rs:35:13:
explicit panic
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

% env RUST_BACKTRACE=1 ./amdgpu_top
There are no the AMD GPU devices found.
thread 'main' panicked at src/main.rs:35:13:
explicit panic
stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_fmt
2: core::panicking::panic_display
3: core::panicking::panic_explicit
4: amdgpu_top::main::panic_cold_explicit
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic.rs:87:13
5: amdgpu_top::main
at /home/vedran/workspace/amdgpu_top/src/main.rs:35:13
6: core::ops::function::FnOnce::call_once
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

% env RUST_BACKTRACE=full ./amdgpu_top
There are no the AMD GPU devices found.
thread 'main' panicked at src/main.rs:35:13:
explicit panic
stack backtrace:
0:     0x14cbf6a51860 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0d22df41a72f543b
1:     0x14cbf6a7ef2b - core::fmt::write::hf2dc21fb3bf42417
2:     0x14cbf6a5427f - std::io::Write::write_fmt::h5f62cfea9e36bf6d
3:     0x14cbf6a5162e - std::sys_common::backtrace::print::hd8888c2893c6effb
4:     0x14cbf6a5821a - std::panicking::default_hook::{{closure}}::h18c73f323706cc09
5:     0x14cbf6a57f0d - std::panicking::default_hook::h81da2ddd2a0d9c9c
6:     0x14cbf6a586f9 - std::panicking::rust_panic_with_hook::h005f80f82882b02a
7:     0x14cbf6a51c34 - std::panicking::begin_panic_handler::{{closure}}::hc308c169babd81fb
8:     0x14cbf6a51a79 - std::sys_common::backtrace::__rust_end_short_backtrace::hd1f19fa3642d785e
9:     0x14cbf6a583f7 - rust_begin_unwind
10:     0x14cbf6a8dae3 - core::panicking::panic_fmt::hf140f60dfedb8b15
11:     0x14cbf6a8dc9c - core::panicking::panic_display::h55465879548752d3
12:     0x14cbf6a8dc43 - core::panicking::panic_explicit::h94f5b9c624fb70ae
13:     0x14cbf588ed4a - amdgpu_top::main::panic_cold_explicit::h01f0da80f9fe6813
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic.rs:87:13
14:     0x14cbf588e101 - amdgpu_top::main::h08aeabc9db0797b7
at /home/vedran/workspace/amdgpu_top/src/main.rs:35:13
15:     0x14cbf589368b - core::ops::function::FnOnce::call_once::he7d388055bc006f1
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
16:     0x14cbf588a62e - std::sys_common::backtrace::__rust_begin_short_backtrace::h602d8d3d1961947b
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
17:     0x14cbf58aff91 - std::rt::lang_start::{{closure}}::h4d51eac4fbe7d46c
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:159:18
18:     0x14cbf6a58297 - std::panicking::try::hbf82ab7fea049861
19:     0x14cbf6a5b598 - std::rt::lang_start_internal::h1da71261e5f3a6ce
20:     0x14cbf58aff6a - std::rt::lang_start::h7362149159010acb
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:158:17
21:     0x14cbf588ed9e - main
22:     0x14d418960a6a - __libc_start1
23:     0x14cbf587d44d - _start
at /usr/src/lib/csu/amd64/crt1_s.S:83
```

**Comment by Umio-Yasuno** [comment]
`explicit panic` is intentional, so the backtrace is not useful.  
I think the problem is probably with `libdrm_amdgpu` .

Does the system detect the AMDGPU device?

> Any chance of FreeBSD support?

If we need code for FreeBSD only, support may be difficult.

**Comment by Umio-Yasuno** [comment]
I do not have a FreeBSD system, nor do I have any knowledge of FreeBSD. So please PR.
